# logging_config.yaml

version: 1
disable_existing_loggers: false
formatters:
  simpleFormatter:
    format: '%(levelname)-8s%(asctime)-22s%(filename)16s->line(%(lineno)s)|%(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  pyfmto_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simpleFormatter
    filename: 'pyfmto.log'
loggers:
  pyfmto:
    level: INFO
    handlers:
      - pyfmto_handler
    propagate: 0
