client:
    pop_size: 50          # Paper: 50
    max_gen: 20           # SOP: 100, MOP: 50, Paper: 20
    lg_type: LG           # LG type used in lcb: LG/L/G
server:
    ensemble_size: 20     # num samples in ensemble
model:
    epoch: 5              # local epoch
    optimizer: sgd        # optimizer of RBF network, sgd/m-sgd/max-gd
    lr: 0.06              # learning rate
    alpha: 1.0            # noisy
